"""Typed command dataclasses for the Jarvis Command Bus."""

from jarvis_engine.commands.base import ResultBase
from jarvis_engine.commands.memory_commands import (
    BrainCompactCommand,
    BrainContextCommand,
    BrainRegressionCommand,
    BrainStatusCommand,
    IngestCommand,
    MemoryMaintenanceCommand,
    MemorySnapshotCommand,
)
from jarvis_engine.commands.voice_commands import (
    PersonaComposeCommand,
    PersonaComposeResult,
    VoiceEnrollCommand,
    VoiceEnrollResult,
    VoiceListCommand,
    VoiceListenCommand,
    VoiceListenResult,
    VoiceListResult,
    VoiceRunCommand,
    VoiceRunResult,
    VoiceSayCommand,
    VoiceSayResult,
    VoiceVerifyCommand,
    VoiceVerifyResult,
)
from jarvis_engine.commands.system_commands import (
    DaemonRunCommand,
    DesktopWidgetCommand,
    GamingModeCommand,
    LogCommand,
    MigrateMemoryCommand,
    MobileDesktopSyncCommand,
    OpenWebCommand,
    SelfHealCommand,
    ServeMobileCommand,
    StatusCommand,
    WeatherCommand,
)
from jarvis_engine.commands.task_commands import (
    QueryCommand,
    QueryResult,
    RouteCommand,
    RouteResult,
    RunTaskCommand,
    RunTaskResult,
    WebResearchCommand,
    WebResearchResult,
)
from jarvis_engine.commands.ops_commands import (
    AutomationRunCommand,
    GrowthAuditCommand,
    GrowthEvalCommand,
    GrowthReportCommand,
    IntelligenceDashboardCommand,
    MissionCancelCommand,
    MissionCancelResult,
    MissionCreateCommand,
    MissionRunCommand,
    MissionStatusCommand,
    OpsBriefCommand,
    OpsExportActionsCommand,
    OpsSyncCommand,
    OpsAutopilotCommand,
)
from jarvis_engine.commands.security_commands import (
    ConnectBootstrapCommand,
    ConnectGrantCommand,
    ConnectStatusCommand,
    OwnerGuardCommand,
    PersonaConfigCommand,
    PhoneActionCommand,
    PhoneSpamGuardCommand,
    RuntimeControlCommand,
)
from jarvis_engine.commands.knowledge_commands import (
    ContradictionListCommand,
    ContradictionResolveCommand,
    FactLockCommand,
    KnowledgeRegressionCommand,
    KnowledgeStatusCommand,
)
from jarvis_engine.commands.harvest_commands import (
    HarvestBudgetCommand,
    HarvestTopicCommand,
    IngestSessionCommand,
)
from jarvis_engine.commands.learning_commands import (
    CrossBranchQueryCommand,
    CrossBranchQueryResult,
    FlagExpiredFactsCommand,
    FlagExpiredFactsResult,
    LearnInteractionCommand,
    LearnInteractionResult,
)
from jarvis_engine.commands.sync_commands import (
    SyncPullCommand,
    SyncPullResult,
    SyncPushCommand,
    SyncPushResult,
    SyncStatusCommand,
    SyncStatusResult,
)
from jarvis_engine.commands.proactive_commands import (
    CostReductionCommand,
    CostReductionResult,
    ProactiveCheckCommand,
    ProactiveCheckResult,
    SelfTestCommand,
    SelfTestResult,
    WakeWordStartCommand,
    WakeWordStartResult,
)
from jarvis_engine.commands.defense_commands import (
    BlockIPCommand,
    BlockIPResult,
    ContainmentOverrideCommand,
    ContainmentOverrideResult,
    ExportForensicsCommand,
    ExportForensicsResult,
    ReviewQuarantineCommand,
    ReviewQuarantineResult,
    SecurityBriefingCommand,
    SecurityBriefingResult,
    SecurityStatusCommand,
    SecurityStatusResult,
    ThreatReportCommand,
    ThreatReportResult,
    UnblockIPCommand,
    UnblockIPResult,
)

__all__ = [
    # Base
    "ResultBase",
    # Memory
    "BrainCompactCommand",
    "BrainContextCommand",
    "BrainRegressionCommand",
    "BrainStatusCommand",
    "IngestCommand",
    "MemoryMaintenanceCommand",
    "MemorySnapshotCommand",
    # Voice
    "PersonaComposeCommand",
    "PersonaComposeResult",
    "VoiceEnrollCommand",
    "VoiceEnrollResult",
    "VoiceListCommand",
    "VoiceListenCommand",
    "VoiceListenResult",
    "VoiceListResult",
    "VoiceRunCommand",
    "VoiceRunResult",
    "VoiceSayCommand",
    "VoiceSayResult",
    "VoiceVerifyCommand",
    "VoiceVerifyResult",
    # System
    "DaemonRunCommand",
    "DesktopWidgetCommand",
    "GamingModeCommand",
    "LogCommand",
    "MigrateMemoryCommand",
    "MobileDesktopSyncCommand",
    "OpenWebCommand",
    "SelfHealCommand",
    "ServeMobileCommand",
    "StatusCommand",
    "WeatherCommand",
    # Task
    "QueryCommand",
    "QueryResult",
    "RouteCommand",
    "RouteResult",
    "RunTaskCommand",
    "RunTaskResult",
    "WebResearchCommand",
    "WebResearchResult",
    # Ops
    "AutomationRunCommand",
    "GrowthAuditCommand",
    "GrowthEvalCommand",
    "GrowthReportCommand",
    "IntelligenceDashboardCommand",
    "MissionCancelCommand",
    "MissionCancelResult",
    "MissionCreateCommand",
    "MissionRunCommand",
    "MissionStatusCommand",
    "OpsBriefCommand",
    "OpsExportActionsCommand",
    "OpsSyncCommand",
    "OpsAutopilotCommand",
    # Security
    "ConnectBootstrapCommand",
    "ConnectGrantCommand",
    "ConnectStatusCommand",
    "OwnerGuardCommand",
    "PersonaConfigCommand",
    "PhoneActionCommand",
    "PhoneSpamGuardCommand",
    "RuntimeControlCommand",
    # Knowledge
    "ContradictionListCommand",
    "ContradictionResolveCommand",
    "FactLockCommand",
    "KnowledgeRegressionCommand",
    "KnowledgeStatusCommand",
    # Harvesting
    "HarvestBudgetCommand",
    "HarvestTopicCommand",
    "IngestSessionCommand",
    # Learning
    "CrossBranchQueryCommand",
    "CrossBranchQueryResult",
    "FlagExpiredFactsCommand",
    "FlagExpiredFactsResult",
    "LearnInteractionCommand",
    "LearnInteractionResult",
    # Sync
    "SyncPullCommand",
    "SyncPullResult",
    "SyncPushCommand",
    "SyncPushResult",
    "SyncStatusCommand",
    "SyncStatusResult",
    # Proactive
    "CostReductionCommand",
    "CostReductionResult",
    "ProactiveCheckCommand",
    "ProactiveCheckResult",
    "SelfTestCommand",
    "SelfTestResult",
    "WakeWordStartCommand",
    "WakeWordStartResult",
    # Defense
    "BlockIPCommand",
    "BlockIPResult",
    "ContainmentOverrideCommand",
    "ContainmentOverrideResult",
    "ExportForensicsCommand",
    "ExportForensicsResult",
    "ReviewQuarantineCommand",
    "ReviewQuarantineResult",
    "SecurityBriefingCommand",
    "SecurityBriefingResult",
    "SecurityStatusCommand",
    "SecurityStatusResult",
    "ThreatReportCommand",
    "ThreatReportResult",
    "UnblockIPCommand",
    "UnblockIPResult",
]
