"""Backward compatibility — canonical location is memory/brain.py"""
from jarvis_engine.memory.brain import *  # noqa: F401,F403
from jarvis_engine.memory.brain import (  # noqa: F401 — private names used by test patches
    _try_hybrid_search,
    _brain_io_lock,
    _load_records,
    _load_index,
    _load_facts,
    _save_index,
    _save_facts,
    _tokenize,
    _pick_branch,
    _summarize,
    _recency_weight,
    _check_dedup,
    _build_brain_record,
    _persist_record,
    _update_index,
    _update_fact_store,
    _extract_fact_candidates,
    _brain_dir,
    _records_path,
    _index_path,
    _facts_path,
    _summaries_path,
    _brain_compact_locked,
    _jsonl_keyword_search,
    _to_float,
    _HASH_MAP_MAX_ENTRIES,
    _HASH_MAP_RECENT_LIMIT,
)
