from __future__ import annotations

import json
from dataclasses import dataclass
from pathlib import Path
from typing import Any


@dataclass
class OpsSnapshot:
    date: str
    tasks: list[dict]
    calendar_events: list[dict]
    emails: list[dict]
    bills: list[dict]
    subscriptions: list[dict]


def _safe_float(value: Any, default: float = 0.0) -> float:
    try:
        return float(value)
    except (TypeError, ValueError):
        return default


def _safe_bool(value: Any) -> bool:
    if isinstance(value, bool):
        return value
    if isinstance(value, (int, float)):
        return value != 0
    return str(value).strip().lower() in {"true", "1", "yes", "y"}


def load_snapshot(path: Path) -> OpsSnapshot:
    raw = json.loads(path.read_text(encoding="utf-8"))
    return OpsSnapshot(
        date=str(raw.get("date", "")),
        tasks=list(raw.get("tasks", [])),
        calendar_events=list(raw.get("calendar_events", [])),
        emails=list(raw.get("emails", [])),
        bills=list(raw.get("bills", [])),
        subscriptions=list(raw.get("subscriptions", [])),
    )


def build_daily_brief(snapshot: OpsSnapshot) -> str:
    urgent_tasks = [t for t in snapshot.tasks if str(t.get("priority", "")).lower() in {"high", "urgent"}]
    unread_important = [
        e
        for e in snapshot.emails
        if (not _safe_bool(e.get("read", False))) and str(e.get("importance", "")).lower() in {"high", "urgent"}
    ]
    due_bills = [b for b in snapshot.bills if str(b.get("status", "")).lower() in {"due", "overdue"}]
    costly_subs = [s for s in snapshot.subscriptions if _safe_float(s.get("monthly_cost", 0.0)) >= 20.0]

    lines = [
        f"Jarvis Daily Brief for {snapshot.date}",
        "",
        f"- Urgent tasks: {len(urgent_tasks)}",
        f"- Important unread emails: {len(unread_important)}",
        f"- Bills due/overdue: {len(due_bills)}",
        f"- High-cost subscriptions (>= $20/mo): {len(costly_subs)}",
        "",
        "Top actions:",
    ]

    top_actions = suggest_actions(snapshot)
    if not top_actions:
        lines.append("- No critical actions detected.")
    else:
        for item in top_actions[:8]:
            lines.append(f"- {item}")
    return "\n".join(lines)


def suggest_actions(snapshot: OpsSnapshot) -> list[str]:
    actions: list[str] = []

    for t in snapshot.tasks:
        pr = str(t.get("priority", "")).lower()
        if pr in {"high", "urgent"}:
            actions.append(f"Complete high-priority task: {t.get('title', 'Untitled')}")

    for e in snapshot.emails:
        if (not _safe_bool(e.get("read", False))) and str(e.get("importance", "")).lower() in {"high", "urgent"}:
            actions.append(f"Reply to critical email: {e.get('subject', 'No subject')}")

    for b in snapshot.bills:
        status = str(b.get("status", "")).lower()
        if status in {"due", "overdue"}:
            actions.append(
                f"Pay bill now: {b.get('name', 'Unnamed bill')} "
                f"(amount ${_safe_float(b.get('amount', 0.0)):.2f})"
            )

    for s in snapshot.subscriptions:
        monthly = _safe_float(s.get("monthly_cost", 0.0))
        usage = _safe_float(s.get("usage_score", 1.0), default=1.0)
        if monthly >= 20.0 and usage <= 0.3:
            actions.append(
                f"Review/cancel low-usage subscription: {s.get('name', 'Unnamed sub')} "
                f"(${monthly:.2f}/mo)"
            )

    for ev in snapshot.calendar_events:
        if str(ev.get("prep_needed", "")).lower() in {"yes", "true", "1"}:
            actions.append(f"Prepare for calendar event: {ev.get('title', 'Untitled event')}")

    return actions


def export_actions_json(actions: list[str], path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    records = []
    for action in actions:
        action_class = "bounded_write"
        if action.startswith("Pay bill now:") or action.startswith("Review/cancel low-usage subscription:"):
            action_class = "privileged"
        records.append(
            {
                "title": action,
                "action_class": action_class,
                "command": "",
                "reason": "Generated by ops planner.",
            }
        )
    path.write_text(json.dumps(records, ensure_ascii=True, indent=2), encoding="utf-8")
